import type { Metadata } from 'next'
import { Inter, EB_Garamond, Merriweather, Alegreya_Sans_SC} from 'next/font/google'
import { Navbar } from '@/components'

import './globals.css'

const inter = Inter({ subsets: ['latin'] })
const garamond = EB_Garamond({subsets: ['latin']})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Navbar/>
      {children}
    </html>
  )
}
